### PR TITLE
Add questionr addins

### PR DESCRIPTION
**Pull request by juba**
I added 3 addins from my `questionr` package, which interactively generate R code for factor recoding, reordering, and variable cutting.

Thanks !

### CODE REVIEW

**Comment by csgillespie** [comment]
Thanks for the request. Could I ask that you just use a single line? I think it would be cleaner if each line was a **package** and not an **addin**.

**Comment by juba** [comment]
Sorry, I didn't see that...

 I just added a commit to put all the addins on one line, I hope it is ok.

Thanks !

**Comment by csgillespie** [comment]
Great. Many thanks

**Comment by csgillespie** [comment]
Many thanks

**Pull request merged**
